
# Use uma imagem base com suporte a Java 17
FROM eclipse-temurin:17-jre-focal

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o JAR diretamente para o contêiner
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

# Comando de entrada para executar o aplicativo Java
ENTRYPOINT ["java", "-jar", "app.jar"]
